"""empty message

Revision ID: 090a5102c3b6
Revises: 300358a6b063
Create Date: 2024-09-07 12:15:59.624153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090a5102c3b6'
down_revision = '300358a6b063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CreatedOn', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('CreatedOn')

    # ### end Alembic commands ###
