"""empty message

Revision ID: 300358a6b063
Revises: 371b2c1a7bfd
Create Date: 2024-09-07 12:08:01.668171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300358a6b063'
down_revision = '371b2c1a7bfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Code', sa.String(length=50), nullable=False),
    sa.Column('CustomerName', sa.String(length=100), nullable=False),
    sa.Column('EmailAddress', sa.String(length=255), nullable=False),
    sa.Column('PhoneNumber', sa.String(length=15), nullable=False),
    sa.Column('PostalAddress', sa.String(length=100), nullable=False),
    sa.Column('Address', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('EmailAddress')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    # ### end Alembic commands ###
