"""account migration

Revision ID: 371b2c1a7bfd
Revises: e6afe8731829
Create Date: 2024-09-06 16:12:42.306996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371b2c1a7bfd'
down_revision = 'e6afe8731829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Group', sa.String(length=100), nullable=False),
    sa.Column('Currency', sa.String(length=100), nullable=False),
    sa.Column('StartBalance', sa.Numeric(precision=24, scale=2), nullable=False),
    sa.Column('CreatedOn', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    # ### end Alembic commands ###
