"""initial migrate

Revision ID: e6afe8731829
Revises: 
Create Date: 2024-09-02 14:11:46.277371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6afe8731829'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('FullNames', sa.String(length=100), nullable=False),
    sa.Column('Username', sa.String(length=100), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('EmailAddress', sa.String(length=255), nullable=False),
    sa.Column('PhoneNumber', sa.String(length=15), nullable=False),
    sa.Column('DateOfBirth', sa.DateTime(), nullable=False),
    sa.Column('ProfilePicture', sa.String(length=255), nullable=True),
    sa.Column('Address', sa.String(length=200), nullable=False),
    sa.Column('CreatedOn', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
